---
version: '3.8'

services:
  speedtest:
    container_name: speedtest
    image: openspeedtest/latest
    restart: unless-stopped
    ports:
      - 5000:3000
      - 5001:3001
    volumes:
      - speedtest-data:/var/log/letsencrypt

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 853:853/udp
      - 8889:3000/tcp
      - 8888:80/tcp
      - 6060:6060/tcp
    volumes:
      - adguard-data:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - helix

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - helix

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    command: '--path.rootfs=/host'
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro,rslave
    networks:
      - helix

  adguard_exporter:
    container_name: adguard_exporter
    image: ebrianne/adguard-exporter:latest
    restart: unless-stopped
    ports:
      - 9617:9617
    environment:
      - adguard_protocol=http
      - adguard_hostname=${ADGUARD_HOST}
      - adguard_username=${ADGUARD_USERNAME}
      - adguard_password=${ADGUARD_PASSWORD}
      - adguard_port=${ADGUARD_PORT}
      - interval=10s
      - log_limit=10000
      - server_port=9617
    networks:
      - helix

  fortigate_exporter:
    container_name: fortigate_exporter
    image: quay.io/bluecmd/fortigate_exporter:latest
    command: ['-auth-file', '/config/fortigate-key.yaml', '-insecure']
    restart: unless-stopped
    volumes:
      - ./config/fortigate/fortigate-key.yaml:/config/fortigate-key.yaml
    ports:
      - 9710:9710
    networks:
      - helix

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: '--config.file=/etc/prometheus/prometheus.yaml'
    restart: unless-stopped
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/config.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - helix

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/custom.ini:/etc/grafana/grafana.ini
    networks:
      - helix

  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    volumes:
      - ./config/homer/assets:/www/assets
    networks:
      - helix

  cloudflare_tunnel:
    container_name: cloudflare_tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: 'tunnel --no-autoupdate run'
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - emby-conf:/config
      - /home/hiep/shared:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  portainer-data:
    driver: local
  adguard-data:
    driver: local
  adguard-conf:
    driver: local
  emby-conf:
    driver: local
  speedtest-data:
    driver: local

networks:
  helix:
    driver: bridge
