global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100', '10.0.10.0:9100']

  - job_name: 'adguard_exporter'
    static_configs:
      - targets: ['adguard_exporter:9617', '10.0.0.10:9617']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'snmp'
  #   static_configs:
  #     - targets:
  #         - 10.0.0.1
  #   metrics_path: /snmp
  #   params:
  #     module: [mikrotik]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: 10.0.10.11:9116
