---
title: 'HelixNest'
subtitle: 'A Helix Nest homepage.'

header: true
footer: false

columns: '4'

defaults:
  layout: list
  colorTheme: 'dark'

theme: default

services:
  - name: 'Monitoring'
    items:
      - name: 'Adguard'
        logo: 'assets/logo/adguard.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        keywords: ''
        url: 'https://grafana.helixnest.com/d/MIBVglomg/adguard?orgId=2&refresh=10s&from=1701761540136&to=1701765140136'
        target: '_blank'

      - name: 'Mikrotik'
        logo: 'assets/logo/mikrotik.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: 'https://grafana.helixnest.com/d/LyX-A_nnk/mikrotik?orgId=2&refresh=1m&from=1701761841449&to=1701765441449&theme=dark'
        target: '_blank'

      - name: 'Fortinet'
        logo: 'assets/logo/fortinet.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: 'https://grafana.helixnest.com/d/T5zWe8WRz/fortigate?orgId=2&refresh=1m&from=1701764341276&to=1701767941276'
        target: '_blank'

      - name: 'Docker'
        logo: 'assets/logo/docker.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: 'https://grafana.helixnest.com/d/4dMaCsRZz/docker?orgId=2&refresh=1m&from=1701761787016&to=1701765387016&theme=dark'
        target: '_blank'

      - name: 'Node'
        logo: 'assets/logo/prometheus.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: 'https://grafana.helixnest.com/d/rYdddlPWk/node?orgId=2&from=1701761879966&to=1701765479966&theme=dark'
        target: '_blank'

  - name: 'Management'
    items:
      - name: 'Adguard'
        logo: 'assets/logo/adguard.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://adguard.helixnest.com'
        target: '_blank'

      - name: 'Mikrotik'
        logo: 'assets/logo/mikrotik.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://mikrotik.helixnest.com'
        target: '_blank'

      - name: 'Fortinet'
        logo: 'assets/logo/fortinet.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://fortinet.helixnest.com'
        target: '_blank'

      - name: 'Portainer'
        logo: 'assets/logo/portainer.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://portainer.helixnest.com'
        target: '_blank'

      - name: 'Hikvision'
        logo: 'assets/logo/hikvision.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://hikvision.helixnest.com'
        target: '_blank'

      - name: 'ODI'
        logo: 'assets/logo/odi.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://odi.helixnest.com'
        target: '_blank'

      - name: 'Aruba'
        logo: 'assets/logo/aruba.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://aruba.helixnest.com'
        target: '_blank'

      - name: 'Grafana'
        logo: 'assets/logo/grafana.png'
        subtitle: 'Manage'
        tag: 'management'
        url: 'https://grafana.helixnest.com'
        target: '_blank'

stylesheet:
  - 'assets/custom.css'
