---
title: 'HelixNest'
subtitle: 'A Helix Nest homepage.'

header: true
footer: false

columns: '4'

defaults:
  layout: list
  colorTheme: 'dark'

theme: default

services:
  - name: 'Monitoring'
    items:
      - name: 'Adguard'
        logo: 'assets/logo/adguard.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        keywords: ''
        url: 'https://www.reddit.com/r/selfhosted/'

      - name: 'Mikrotik'
        logo: 'assets/logo/mikrotik.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: '#'

      - name: 'Node'
        logo: 'assets/logo/prometheus.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: '#'

      - name: 'Docker'
        logo: 'assets/logo/docker.png'
        subtitle: 'Visualize'
        tag: 'metrics'
        url: '#'

  - name: 'Management'
    items:
      - name: 'Portainer'
        logo: 'assets/logo/portainer.png'
        subtitle: 'Manage'
        tag: 'management'
        url: '#'

stylesheet:
  - 'assets/custom.css'
