---
title: 'HelixNest'
subtitle: 'A Helix Nest homepage.'

header: true
footer: false

columns: '4'

defaults:
  layout: list
  colorTheme: 'dark'

theme: default

services:
  - name: 'Monitoring'
    items:
      - name: 'Adguard'
        logo: 'assets/logo/adguard.png'
        subtitle: 'Visualize'
        url: 'https://grafana.helixnest.com/d/MIBVglomg/adguard?orgId=2&refresh=1m&from=now-1h&to=now'
        target: '_blank'

      - name: 'Mikrotik'
        logo: 'assets/logo/mikrotik.png'
        subtitle: 'Visualize'
        url: 'https://grafana.helixnest.com/d/LyX-A_nnk/mikrotik?orgId=2&refresh=1m&from=now-1h&to=now'
        target: '_blank'

      - name: 'Fortinet'
        logo: 'assets/logo/fortinet.png'
        subtitle: 'Visualize'
        url: 'https://grafana.helixnest.com/d/T5zWe8WRz/fortigate?orgId=2&refresh=1m'
        target: '_blank'

      - name: 'Docker'
        logo: 'assets/logo/docker.png'
        subtitle: 'Visualize'
        url: 'https://grafana.helixnest.com/d/4dMaCsRZz/docker?orgId=2&refresh=1m&from=now-1h&to=now'
        target: '_blank'

      - name: 'Node'
        logo: 'assets/logo/prometheus.png'
        subtitle: 'Visualize'
        url: 'https://grafana.helixnest.com/d/rYdddlPWk/node?orgId=2&refresh=1m&from=now-1h&to=now'
        target: '_blank'

  - name: 'Management'
    items:
      - name: 'Adguard'
        logo: 'assets/logo/adguard.png'
        subtitle: 'Manage'
        url: 'https://adguard.helixnest.com'
        target: '_blank'

      - name: 'Mikrotik'
        logo: 'assets/logo/mikrotik.png'
        subtitle: 'Manage'
        url: 'https://mikrotik.helixnest.com'
        target: '_blank'

      - name: 'Fortinet'
        logo: 'assets/logo/fortinet.png'
        subtitle: 'Manage'
        url: 'https://fortinet.helixnest.com'
        target: '_blank'

      - name: 'Portainer'
        logo: 'assets/logo/portainer.png'
        subtitle: 'Manage'
        url: 'https://portainer.helixnest.com'
        target: '_blank'

      - name: 'Hikvision'
        logo: 'assets/logo/hikvision.png'
        subtitle: 'Manage'
        url: 'https://hikvision.helixnest.com'
        target: '_blank'

      - name: 'ODI'
        logo: 'assets/logo/odi.png'
        subtitle: 'Manage'
        url: 'https://odi.helixnest.com'
        target: '_blank'

      - name: 'Aruba'
        logo: 'assets/logo/aruba.png'
        subtitle: 'Manage'
        url: 'https://aruba.helixnest.com'
        target: '_blank'

      - name: 'Grafana'
        logo: 'assets/logo/grafana.png'
        subtitle: 'Manage'
        url: 'https://grafana.helixnest.com'
        target: '_blank'

  - name: 'Utilities'
    items:
      - name: 'Speedtest'
        logo: 'assets/logo/speedtest.png'
        subtitle: 'Utilities'
        url: 'https://speedtest.helixnest.com'
        target: '_blank'

stylesheet:
  - 'assets/custom.css'
